// src/components/Conversor.vue
<template>
  <div class="conversor">
    <h2>{{ moedaA }} Para {{ moedaB }}</h2>
    <input type="text" v-model="moedaA_value" v-bind:placeholder="moedaA" />
    <br />
    <input type="button" value="Converter" v-on:click="converter" />
    <h2>{{ moedaB_value }}</h2>
  </div>
</template>

<script>
export default {
  name: "conversor",
  props: ["moedaA", "moedaB"],
  data() {
    return {
      moedaA_value: "",
      moedaB_value: 0,
    };
  },
  methods: {
    converter() {
      let de_para = this.moedaA + "_" + this.moedaB;
      let url =
        "https://free.currconv.com/api/v7/convert?apiKey=a3242a2fda52f3ffa2ed&q=" +
        de_para +
        "&compact=y";

      fetch(url)
        .then((res) => {
          return res.json();
        })
        .then((json) => {
          let cotacao = json[de_para].val;
          this.moedaB_value = (cotacao * parseFloat(this.moedaA_value)).toFixed(
            2
          );
        });
    },
  },
};
</script>

<style scoped>
.conversor {
  padding: 20px;
  max-width: 300px;
  box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
}
</style>

// src/components/Conversor.jsx
import React, { useState } from 'react'
import './Conversor.css'

export default function Conversor({moedaA, moedaB}) {


    const [moedaAValue, setMoedaAValue] = useState()
    const [moedaBValue, setMoedaBValue] = useState()

   const  converter = () =>{
    
    fetch(`https://api.freecurrencyapi.com/v1/latest?apikey=edVxAVo4Z0GCYpU56zNG8zW5fgLiDGB2898ZOWyE&currencies=${moedaB}&base_currency=${moedaA}`)
    .then(response => response.json())
    .then(data => {
        let cambio  = Object.values(data.data)[0]
        console.log(data.data)
        console.log(cambio, moedaAValue)
        setMoedaBValue((moedaAValue * cambio).toFixed(2))
    })
    .catch(error => console.error(error));

   }

    return (
        <div className='Conversor'>
            <h2>{moedaA} Para {moedaB}</h2>
            <input type="text" value={moedaAValue} onChange={(e) => setMoedaAValue(e.target.value)}/>
            <br />
            <button onClick={converter}>Converter</button>
            <h2>{moedaBValue} {moedaB}</h2>
      </div>
      )
}
